/**
 * Master Firearms Manufacturer Registry — v2
 * 
 * Sources used per manufacturer (priority order):
 *   1. directNewsUrl  — manufacturer's own /news or /blog page (scraped)
 *   2. prnKeyword     — PRNewswire RSS keyword search
 *   3. rssUrl         — direct RSS feed if available
 */

export const MANUFACTURERS = [
  // ── PISTOLS / HANDGUNS ──────────────────────────────────────────────────────
  {
    brand: 'Glock',
    website: 'https://us.glock.com',
    directNewsUrl: 'https://us.glock.com/en/news',
    prnKeyword: 'GLOCK',
    country: 'Austria/USA',
    category: ['Pistol'],
    logoKeywords: ['glock'],
  },
  {
    brand: 'SIG Sauer',
    website: 'https://www.sigsauer.com',
    directNewsUrl: 'https://www.sigsauer.com/blog/',
    prnKeyword: 'SIG SAUER',
    country: 'USA/Germany',
    category: ['Pistol', 'Rifle', 'Suppressor', 'Optic'],
    logoKeywords: ['sig sauer', 'sig-sauer'],
  },
  {
    brand: 'Smith & Wesson',
    website: 'https://www.smith-wesson.com',
    directNewsUrl: 'https://www.smith-wesson.com/news',
    prnKeyword: 'Smith Wesson',
    country: 'USA',
    category: ['Pistol', 'Revolver', 'Rifle'],
    logoKeywords: ['smith & wesson', 'smith and wesson'],
  },
  {
    brand: 'Ruger',
    website: 'https://www.ruger.com',
    directNewsUrl: 'https://www.ruger.com/micros/newProducts/',
    rssUrl: 'https://www.ruger.com/micros/newProducts/rss',
    prnKeyword: 'Sturm Ruger',
    country: 'USA',
    category: ['Pistol', 'Revolver', 'Rifle', 'Shotgun'],
    logoKeywords: ['ruger', 'sturm ruger'],
  },
  {
    brand: 'Springfield Armory',
    website: 'https://www.springfield-armory.com',
    directNewsUrl: 'https://www.springfield-armory.com/news/',
    prnKeyword: 'Springfield Armory',
    country: 'USA',
    category: ['Pistol', 'Rifle'],
    logoKeywords: ['springfield armory'],
  },
  {
    brand: 'Beretta',
    website: 'https://www.beretta.com',
    directNewsUrl: 'https://www.beretta.com/en-us/news/',
    prnKeyword: 'Beretta USA',
    country: 'Italy/USA',
    category: ['Pistol', 'Shotgun', 'Rifle'],
    logoKeywords: ['beretta'],
  },
  {
    brand: 'Walther',
    website: 'https://www.waltherarms.com',
    directNewsUrl: 'https://www.waltherarms.com/news/',
    prnKeyword: 'Walther Arms',
    country: 'Germany',
    category: ['Pistol'],
    logoKeywords: ['walther'],
  },
  {
    brand: 'HK USA',
    website: 'https://www.hk-usa.com',
    directNewsUrl: 'https://www.hk-usa.com/news/',
    prnKeyword: 'Heckler Koch',
    country: 'Germany/USA',
    category: ['Pistol', 'Rifle'],
    logoKeywords: ['heckler', 'h&k', 'hk usa'],
  },
  {
    brand: 'CZ-USA',
    website: 'https://cz-usa.com',
    directNewsUrl: 'https://cz-usa.com/news/',
    prnKeyword: 'CZ-USA',
    country: 'Czech Republic',
    category: ['Pistol', 'Rifle', 'Shotgun'],
    logoKeywords: ['cz-usa', 'cz usa'],
  },
  {
    brand: 'Kimber',
    website: 'https://www.kimberamerica.com',
    directNewsUrl: 'https://www.kimberamerica.com/news',
    prnKeyword: 'Kimber America',
    country: 'USA',
    category: ['Pistol'],
    logoKeywords: ['kimber'],
  },
  {
    brand: 'Taurus',
    website: 'https://www.taurususa.com',
    directNewsUrl: 'https://www.taurususa.com/news/',
    prnKeyword: 'Taurus USA',
    country: 'Brazil/USA',
    category: ['Pistol', 'Revolver', 'Rifle'],
    logoKeywords: ['taurus usa'],
  },
  {
    brand: 'FN America',
    website: 'https://www.fnamerica.com',
    directNewsUrl: 'https://www.fnamerica.com/news/',
    prnKeyword: 'FN America',
    country: 'Belgium/USA',
    category: ['Pistol', 'Rifle'],
    logoKeywords: ['fn america', 'fabrique nationale'],
  },
  {
    brand: 'Kel-Tec',
    website: 'https://www.keltecweapons.com',
    directNewsUrl: 'https://www.keltecweapons.com/news/',
    prnKeyword: 'Kel-Tec',
    country: 'USA',
    category: ['Pistol', 'Rifle', 'Shotgun'],
    logoKeywords: ['kel-tec', 'keltec'],
  },
  {
    brand: 'Staccato',
    website: 'https://staccato2011.com',
    directNewsUrl: 'https://staccato2011.com/blogs/news',
    prnKeyword: 'Staccato 2011',
    country: 'USA',
    category: ['Pistol'],
    logoKeywords: ['staccato'],
  },
  {
    brand: 'Shadow Systems',
    website: 'https://www.shadowsystemscorp.com',
    directNewsUrl: 'https://www.shadowsystemscorp.com/blogs/news',
    prnKeyword: 'Shadow Systems',
    country: 'USA',
    category: ['Pistol'],
    logoKeywords: ['shadow systems'],
  },
  {
    brand: 'Canik USA',
    website: 'https://canikusa.com',
    directNewsUrl: 'https://canikusa.com/news/',
    prnKeyword: 'Canik USA',
    country: 'Turkey/USA',
    category: ['Pistol'],
    logoKeywords: ['canik'],
  },
  {
    brand: 'Fusion Firearms',
    website: 'https://fusionfirearms.com',
    directNewsUrl: 'https://fusionfirearms.com/videovault/',
    prnKeyword: 'Fusion Firearms',
    country: 'USA',
    category: ['Pistol'],
    logoKeywords: ['fusion firearms'],
    notes: 'Magento site. Newsroom at /videovault/. Key products: XP Pro, XF Pro, XP Comp, XP 3C, custom 1911s. Founded by Bob Serva. Collaboration with Ermox on XP/XF platform.',
  },

  // ── RIFLES / LONG GUNS ─────────────────────────────────────────────────────
  {
    brand: 'Daniel Defense',
    website: 'https://danieldefense.com',
    directNewsUrl: 'https://danieldefense.com/blog/',
    prnKeyword: 'Daniel Defense',
    country: 'USA',
    category: ['Rifle'],
    logoKeywords: ['daniel defense'],
  },
  {
    brand: 'BCM (Bravo Company)',
    website: 'https://www.bravocompanymfg.com',
    directNewsUrl: 'https://www.bravocompanymfg.com/blog/',
    prnKeyword: 'Bravo Company',
    country: 'USA',
    category: ['Rifle'],
    logoKeywords: ['bravo company', 'bcm'],
  },
  {
    brand: 'LWRC International',
    website: 'https://www.lwrci.com',
    directNewsUrl: 'https://www.lwrci.com/blogs/news',
    prnKeyword: 'LWRC',
    country: 'USA',
    category: ['Rifle'],
    logoKeywords: ['lwrc', 'lwrci'],
  },
  {
    brand: 'LaRue Tactical',
    website: 'https://www.larue.com',
    directNewsUrl: 'https://www.larue.com/pages/news',
    prnKeyword: 'LaRue Tactical',
    country: 'USA',
    category: ['Rifle'],
    logoKeywords: ['larue'],
  },
  {
    brand: 'Savage Arms',
    website: 'https://www.savagearms.com',
    directNewsUrl: 'https://www.savagearms.com/news',
    prnKeyword: 'Savage Arms',
    country: 'USA',
    category: ['Rifle', 'Pistol'],
    logoKeywords: ['savage arms'],
  },
  {
    brand: 'Tikka',
    website: 'https://www.tikka.fi/en',
    directNewsUrl: 'https://www.tikka.fi/en/news',
    prnKeyword: 'Tikka',
    country: 'Finland',
    category: ['Rifle'],
    logoKeywords: ['tikka'],
  },
  {
    brand: 'Christensen Arms',
    website: 'https://www.christensenarms.com',
    directNewsUrl: 'https://www.christensenarms.com/blogs/news',
    prnKeyword: 'Christensen Arms',
    country: 'USA',
    category: ['Rifle'],
    logoKeywords: ['christensen arms'],
  },
  {
    brand: 'Barrett Firearms',
    website: 'https://barrett.net',
    directNewsUrl: 'https://barrett.net/news/',
    prnKeyword: 'Barrett Firearms',
    country: 'USA',
    category: ['Rifle'],
    logoKeywords: ['barrett'],
  },
  {
    brand: 'IWI US',
    website: 'https://iwi.us',
    directNewsUrl: 'https://iwi.us/news/',
    prnKeyword: 'IWI US',
    country: 'Israel/USA',
    category: ['Pistol', 'Rifle'],
    logoKeywords: ['iwi us', 'israel weapon'],
  },

  // ── SHOTGUNS ───────────────────────────────────────────────────────────────
  {
    brand: 'Mossberg',
    website: 'https://www.mossberg.com',
    directNewsUrl: 'https://www.mossberg.com/news/',
    prnKeyword: 'Mossberg',
    country: 'USA',
    category: ['Shotgun', 'Rifle'],
    logoKeywords: ['mossberg', 'o.f. mossberg'],
  },
  {
    brand: 'Benelli',
    website: 'https://www.benelliusa.com',
    directNewsUrl: 'https://www.benelliusa.com/news/',
    prnKeyword: 'Benelli USA',
    country: 'Italy',
    category: ['Shotgun', 'Rifle'],
    logoKeywords: ['benelli'],
  },
  {
    brand: 'Browning',
    website: 'https://www.browning.com',
    directNewsUrl: 'https://www.browning.com/news/',
    prnKeyword: 'Browning',
    country: 'USA',
    category: ['Shotgun', 'Rifle', 'Pistol'],
    logoKeywords: ['browning'],
  },
  {
    brand: 'Winchester Repeating Arms',
    website: 'https://www.winchesterguns.com',
    directNewsUrl: 'https://www.winchesterguns.com/news/',
    prnKeyword: 'Winchester Repeating Arms',
    country: 'USA',
    category: ['Rifle', 'Shotgun'],
    logoKeywords: ['winchester repeating', 'winchester firearms'],
  },
  {
    brand: 'Remington',
    website: 'https://www.remington.com',
    directNewsUrl: 'https://www.remington.com/news/',
    prnKeyword: 'Remington Arms',
    country: 'USA',
    category: ['Rifle', 'Shotgun', 'Pistol'],
    logoKeywords: ['remington arms', 'remington firearms'],
  },

  // ── 1911 / CUSTOM / PRECISION ──────────────────────────────────────────────
  {
    brand: 'Wilson Combat',
    website: 'https://www.wilsoncombat.com',
    directNewsUrl: 'https://www.wilsoncombat.com/news/',
    prnKeyword: 'Wilson Combat',
    country: 'USA',
    category: ['Pistol', 'Rifle'],
    logoKeywords: ['wilson combat'],
  },
  {
    brand: 'Nighthawk Custom',
    website: 'https://www.nighthawkcustom.com',
    directNewsUrl: 'https://www.nighthawkcustom.com/news/',
    prnKeyword: 'Nighthawk Custom',
    country: 'USA',
    category: ['Pistol'],
    logoKeywords: ['nighthawk custom'],
  },
  {
    brand: 'Les Baer Custom',
    website: 'https://www.lesbaer.com',
    directNewsUrl: 'https://www.lesbaer.com/news/',
    prnKeyword: 'Les Baer',
    country: 'USA',
    category: ['Pistol', 'Rifle'],
    logoKeywords: ['les baer'],
  },

  // ── SUPPRESSORS / NFA ──────────────────────────────────────────────────────
  {
    brand: 'SilencerCo',
    website: 'https://www.silencerco.com',
    directNewsUrl: 'https://www.silencerco.com/news/',
    prnKeyword: 'SilencerCo',
    country: 'USA',
    category: ['Suppressor'],
    logoKeywords: ['silencerco'],
  },
  {
    brand: 'Dead Air Silencers',
    website: 'https://www.deadairsilencers.com',
    directNewsUrl: 'https://www.deadairsilencers.com/news/',
    prnKeyword: 'Dead Air Silencers',
    country: 'USA',
    category: ['Suppressor'],
    logoKeywords: ['dead air'],
  },
  {
    brand: 'Gemtech',
    website: 'https://www.gem-tech.com',
    directNewsUrl: 'https://www.gem-tech.com/news/',
    prnKeyword: 'Gemtech',
    country: 'USA',
    category: ['Suppressor'],
    logoKeywords: ['gemtech'],
  },
  {
    brand: 'Banish Suppressors',
    website: 'https://www.banishsuppressors.com',
    directNewsUrl: 'https://www.banishsuppressors.com/blogs/news',
    prnKeyword: 'Banish Suppressor',
    country: 'USA',
    category: ['Suppressor'],
    logoKeywords: ['banish'],
  },
]

export const ALL_PRN_KEYWORDS = MANUFACTURERS.map(m => m.prnKeyword)

export function matchManufacturer(text) {
  const lower = text.toLowerCase()
  return MANUFACTURERS.find(m =>
    m.logoKeywords.some(kw => lower.includes(kw.toLowerCase()))
  ) || null
}
