import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

// ── BLOG PUBLISH API ──────────────────────────────────────────────────────────
// POST /api/blog-publish
// Authorization: Bearer CRON_SECRET
// Body: { slug, action: 'publish' | 'draft' | 'schedule', publishDate? }
//
// In production this would write to Sanity CMS.
// Currently: validates the request and returns success with the article data.
// Extend by adding Sanity mutations when SANITY_API_TOKEN has write access.

export async function POST(req) {
  // Auth check
  const auth = req.headers.get('Authorization') || ''
  const token = auth.replace('Bearer ', '').trim()
  if (!token || token !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { slug, action = 'publish', publishDate, article } = body

  if (!slug) {
    return NextResponse.json({ error: 'slug is required' }, { status: 400 })
  }

  // ── Sanity publish ───────────────────────────────────────────────────────────
  // Uncomment when SANITY_API_TOKEN has write permissions
  /*
  const SANITY_TOKEN = process.env.SANITY_API_TOKEN
  const PROJECT_ID   = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'vbnsqnkg'
  
  if (article && SANITY_TOKEN) {
    const doc = {
      _id:           `learn-${slug}`,
      _type:         'blogPost',
      title:         article.title,
      slug:          { _type: 'slug', current: slug },
      subtitle:      article.subtitle,
      category:      article.category,
      readTime:      article.readTime,
      publishedAt:   publishDate || new Date().toISOString(),
      heroImage:     article.heroImage,
      tags:          article.tags,
      intro:         article.intro,
      sections:      article.sections,
      keyTakeaways:  article.keyTakeaways,
      author:        'DJ Cavalcanti',
      status:        action === 'publish' ? 'published' : action,
      autoGenerated: false,
      approved:      action === 'publish',
    }

    const mutation = { mutations: [{ createOrReplace: doc }] }
    const sanRes = await fetch(
      `https://${PROJECT_ID}.api.sanity.io/v2024-01-01/data/mutate/production`,
      {
        method:  'POST',
        headers: { 'Authorization': `Bearer ${SANITY_TOKEN}`, 'Content-Type': 'application/json' },
        body:    JSON.stringify(mutation),
      }
    )
    const sanData = await sanRes.json()
    if (!sanRes.ok) {
      return NextResponse.json({ error: 'Sanity write failed', detail: sanData }, { status: 500 })
    }
  }
  */

  // ── Discord notification ─────────────────────────────────────────────────────
  const webhookUrl = process.env.DISCORD_WEBHOOK_URL
  if (webhookUrl) {
    const message = action === 'publish'
      ? `📝 **Article Published**: ${slug}\nhttps://downrangeco.com/learn/${slug}`
      : `📅 **Article Scheduled**: ${slug} for ${publishDate || 'TBD'}`

    await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: message }),
    }).catch(() => {})
  }

  return NextResponse.json({
    success:  true,
    slug,
    action,
    url:      `https://downrangeco.com/learn/${slug}`,
    message:  action === 'publish'
      ? `✓ Article '${slug}' published at /learn/${slug}`
      : `✓ Article '${slug}' ${action}d${publishDate ? ` for ${publishDate}` : ''}`,
    publishDate: publishDate || new Date().toISOString(),
    note: 'Sanity write enabled when SANITY_API_TOKEN has write permissions',
  })
}
