require('dotenv').config()
const axios = require('axios')
const Parser = require('rss-parser')
const { rewriteWithClaude, isDuplicate, publishToSanity, notifyBreaking, notifyError, sleep } = require('../utils')

const parser = new Parser()

const RSS_FEEDS = [
  { name: 'The Firearm Blog', url: 'https://www.thefirearmblog.com/blog/feed/' },
  { name: 'AmmoLand', url: 'https://www.ammoland.com/feed/' },
  { name: 'TTAG', url: 'https://www.thetruthaboutguns.com/feed/' },
  { name: 'NRA-ILA', url: 'https://www.nraila.org/rss/' },
  { name: 'Guns.com', url: 'https://www.guns.com/feed' },
]

async function fetchNewsAPI() {
  if (!process.env.NEWSAPI_KEY) return []
  try {
    const res = await axios.get('https://newsapi.org/v2/everything', {
      params: {
        q: 'firearms OR "Second Amendment" OR ATF OR "gun rights" OR "concealed carry"',
        sortBy: 'publishedAt', pageSize: 50, language: 'en',
        apiKey: process.env.NEWSAPI_KEY
      }
    })
    return res.data.articles.map(a => ({
      title: a.title, description: a.description, url: a.url,
      source: a.source?.name, publishedAt: a.publishedAt,
      image: a.urlToImage
    }))
  } catch (err) {
    console.error('NewsAPI error:', err.message)
    return []
  }
}

async function fetchGNews() {
  if (!process.env.GNEWS_KEY) return []
  try {
    const res = await axios.get('https://gnews.io/api/v4/search', {
      params: {
        q: 'firearms OR "gun law" OR "Second Amendment"',
        lang: 'en', max: 25, token: process.env.GNEWS_KEY
      }
    })
    return res.data.articles.map(a => ({
      title: a.title, description: a.description, url: a.url,
      source: a.source?.name, publishedAt: a.publishedAt,
      image: a.image
    }))
  } catch (err) {
    console.error('GNews error:', err.message)
    return []
  }
}

async function fetchRSS() {
  const all = []
  for (const feed of RSS_FEEDS) {
    try {
      const result = await parser.parseURL(feed.url)
      const items = result.items.slice(0, 15).map(i => ({
        title: i.title, description: i.contentSnippet || i.content,
        url: i.link, source: feed.name, publishedAt: i.pubDate,
        image: null
      }))
      all.push(...items)
      await sleep(500)
    } catch (err) {
      console.error(`RSS error (${feed.name}):`, err.message)
    }
  }
  return all
}

async function processNewsItem(item) {
  if (!item.title || !item.url) return null
  if (isDuplicate(item.url)) return null

  const ai = await rewriteWithClaude(item)

  const doc = {
    _id: 'news-' + require('crypto').createHash('md5').update(item.url).digest('hex'),
    _type: 'newsArticle',
    title: item.title,
    excerpt: ai.summary || item.description?.slice(0, 200),
    category: ai.category || 'news',
    urgencyScore: ai.urgencyScore || 3,
    tags: ai.tags || [],
    relatedStates: ai.relatedStates || [],
    source: item.source,
    externalUrl: item.url,
    heroImage: item.image ? { _type: 'externalImage', url: item.image } : undefined,
    publishedAt: item.publishedAt || new Date().toISOString(),
    autoGenerated: true,
    approved: true,
    dedupHash: require('crypto').createHash('md5').update(item.url).digest('hex')
  }

  await publishToSanity(doc)

  if (ai.isBreaking || ai.urgencyScore >= 8) {
    const alertDoc = {
      _id: 'alert-' + doc.dedupHash,
      _type: 'breakingAlert',
      headline: item.title,
      url: item.url,
      source: item.source,
      urgencyScore: ai.urgencyScore,
      active: true,
      publishedAt: doc.publishedAt
    }
    await publishToSanity(alertDoc)
    await notifyBreaking({ ...item, urgencyScore: ai.urgencyScore, summary: ai.summary })
  }

  return doc
}

async function runNewsFeed() {
  console.log('[NEWS] Starting news feed pull...')
  const t = Date.now()

  let allItems = []
  const [newsapi, gnews, rss] = await Promise.all([fetchNewsAPI(), fetchGNews(), fetchRSS()])
  allItems = [...newsapi, ...gnews, ...rss]

  // Sort by date, newest first
  allItems.sort((a, b) => new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0))

  let done = 0, failed = 0
  for (const item of allItems) {
    try {
      const result = await processNewsItem(item)
      if (result) done++
    } catch (err) {
      failed++
      console.error('Process error:', err.message)
    }
    await sleep(800) // Rate limit Claude API
  }

  console.log(`[NEWS] Done. ${done} published, ${failed} failed. ${Date.now() - t}ms`)
  return { done, failed, total: allItems.length }
}

module.exports = { runNewsFeed }
if (require.main === module) runNewsFeed().catch(console.error)
