#!/usr/bin/env python3
"""Delete off-topic Brazil/Canada articles that slipped through before GATE filters."""
import urllib.request, urllib.parse, json, os, re, time

TOKEN   = os.environ.get("SANITY_TOKEN","").replace("ST=","")
PROJECT = "vbnsqnkg"
BASE    = f"https://{PROJECT}.api.sanity.io/v2024-01-01/data"
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}

def q(query):
    url = f"{BASE}/query/production?query=" + urllib.parse.quote(query)
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {TOKEN}"})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())["result"]

def mutate(mutations):
    body = json.dumps({"mutations": mutations}).encode()
    req  = urllib.request.Request(f"{BASE}/mutate/production", data=body, headers=HEADERS, method="POST")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())

# Firearms keywords (abbreviated — same logic as GATE 4)
ARMS = re.compile(r'\b(gun|firearm|arma|pistol|rifle|carabina|munição|ammo|atirador|cac|tiro|craf|sinarm|exército.*arm|policia.*arm|calibre|cartucho|fuzil|revólver|espingarda|suppressore|silencer|carry|porte)\b', re.I)

def is_arms(title, body=''):
    return bool(ARMS.search((title or '') + ' ' + (body or '')[:200]))

# Fetch all Brazil auto-generated articles
br = q('*[_type=="brazilContent" && autoGenerated==true] | order(publishedAt desc) [0...100] {_id,title,source}')
ca = q('*[_type=="canadaContent" && autoGenerated==true] | order(publishedAt desc) [0...100] {_id,title,source}')

to_delete = []
for doc in br + ca:
    if not is_arms(doc.get('title','')):
        to_delete.append(doc)
        print(f"OFF-TOPIC [{doc.get('source','')}]: {doc.get('title','')[:70]}")

print(f"\nFound {len(to_delete)} off-topic articles")
if to_delete:
    mutations = [{"delete": {"id": d["_id"]}} for d in to_delete]
    result = mutate(mutations)
    print(f"Deleted: {len(result.get('results',[]))}")
else:
    print("Nothing to delete")
