#!/usr/bin/env python3
"""Delete off-topic Brazil/Canada articles that slipped through before GATE filters."""
import urllib.request, urllib.parse, json, os, re, time

TOKEN   = os.environ.get("SANITY_TOKEN","").replace("ST=","")
PROJECT = "vbnsqnkg"
BASE    = f"https://{PROJECT}.api.sanity.io/v2024-01-01/data"
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}

def q(query):
    url = f"{BASE}/query/production?query=" + urllib.parse.quote(query)
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {TOKEN}"})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())["result"]

def mutate(mutations):
    body = json.dumps({"mutations": mutations}).encode()
    req  = urllib.request.Request(f"{BASE}/mutate/production", data=body, headers=HEADERS, method="POST")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())

# Firearms keywords (abbreviated — same logic as GATE 4)
# Full keyword list — mirrors GATE 4 in news.js, extended with CA/BR terms
ARMS_KEYWORDS = [
    'gun','guns','firearm','firearms','pistol','rifle','shotgun','revolver','handgun','handguns',
    'ammo','ammunition','caliber','calibre','cartridge','bullet','suppressor','silencer',
    'magazine','trigger','barrel','assault weapon','nra','saf','fpc','goa','atf','batfe',
    'background check','nics','ffl','bruen','heller','ghost gun','ar-15','ar15','1911','2011',
    'shooting','hunting','hunter','self-defense','open carry','gun store','gunsmith',
    'concealed carry','ccw','constitutional carry','red flag','second amendment','2nd amendment',
    'muzzle device','red dot','nfa','fusion firearms',
    # Canada-specific
    'pal','rpal','c-21','c-71','bill c-21','bill c-71','ccfr','nfa canada','crime gun',
    'handgun ban','handgun freeze','oic','firearm ban','gun ban','gun rights','firearms act',
    'saskatchewan','alberta','firearms law','gun law','gun owner',
    # Brazil-specific  
    'cac','tiro esportivo','arma de fogo','porte de arma','clube de tiro',
    'policia federal','exercito','exército','fuzil','espingarda','craf','sinarm','munição',
]
ARMS = re.compile(r'\b(' + '|'.join(re.escape(k) for k in ARMS_KEYWORDS) + r')\b', re.I)

def is_arms(title, body=''):
    return bool(ARMS.search((title or '') + ' ' + (body or '')[:200]))

# Fetch all Brazil auto-generated articles
br = q('*[_type=="brazilContent" && autoGenerated==true] | order(publishedAt desc) [0...100] {_id,title,source}')
ca = q('*[_type=="canadaContent" && autoGenerated==true] | order(publishedAt desc) [0...100] {_id,title,source}')

to_delete = []
for doc in br + ca:
    if not is_arms(doc.get('title','')):
        to_delete.append(doc)
        print(f"OFF-TOPIC [{doc.get('source','')}]: {doc.get('title','')[:70]}")

print(f"\nFound {len(to_delete)} off-topic articles")
if to_delete:
    mutations = [{"delete": {"id": d["_id"]}} for d in to_delete]
    result = mutate(mutations)
    print(f"Deleted: {len(result.get('results',[]))}")
else:
    print("Nothing to delete")
