import urllib.request, urllib.parse, json, os

TOKEN = os.environ.get("SANITY_TOKEN","").replace("ST=","")
PROJECT = "vbnsqnkg"

def q(query):
    url = f"https://{PROJECT}.api.sanity.io/v2024-01-01/data/query/production?query=" + urllib.parse.quote(query)
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {TOKEN}"})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())["result"]

# Full details on the broken article
r = q('*[_type=="canadaContent" && slug.current=="liberals-extend-gun-confiscation-amnesty-while-continuing-seizures"][0]{_id,title,slug,active,type,imageUrl,body,sourceUrl,autoGenerated,qualityReviewed}')
print("Full doc:")
for k,v in r.items():
    val = str(v)[:120] if k != "body" else f"[{len(v or '')} chars]"
    print(f"  {k}: {val}")
