import urllib.request, urllib.parse, json, os

TOKEN = os.environ.get("SANITY_TOKEN","").replace("ST=","")
PROJECT = "vbnsqnkg"

def q(query):
    url = f"https://{PROJECT}.api.sanity.io/v2024-01-01/data/query/production?query=" + urllib.parse.quote(query)
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {TOKEN}"})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())["result"]

# Check for the specific article by slug variants
slugs = [
    "liberals-extend-gun-confiscation-amnesty-while-continuing-seizures",
    "canada-liberals-extend-gun-confiscation-amnesty-while-continuing-seizures",
    "canada-gun-rights-news-week-of-2026-june-01",
]
for s in slugs:
    r = q(f'*[_type=="canadaContent" && slug.current=="{s}"]{{_id,title,active,imageUrl,body}}')
    if r:
        print(f"FOUND [{s}]:", r[0].get("title","")[:60], "active:", r[0].get("active"), "img:", bool(r[0].get("imageUrl")), "body:", len(r[0].get("body","") or ""))
    else:
        print(f"NOT FOUND: {s}")

# Show all canadaContent articles
all_ca = q('*[_type=="canadaContent" && type=="article"] | order(publishedAt desc) [0...30] {_id,title,slug,active,imageUrl,autoGenerated,publishedAt}')
print(f"\nAll canadaContent articles ({len(all_ca)}):")
for a in all_ca:
    slug = a.get("slug",{}).get("current","")
    print(f"  [{('ACTIVE' if a.get('active') else 'INACTIVE'):8s}] [{('AI' if not a.get('autoGenerated') else 'RSS'):3s}] img={bool(a.get('imageUrl'))} {slug[:55]:55s} | {a.get('title','')[:50]}")
