#!/usr/bin/env python3
"""
patch-intl-articles.py
Patches existing Canada and Brazil autoGenerated articles that have:
  1. Raw RSS body (no <h2> tags, under 400 words) — queues for quality-rewrite
  2. Missing imageUrl — fetches from sourceUrl OG tags
  3. Specific broken article fix: liberals-extend-gun-confiscation...

Usage:
  SANITY_TOKEN=xxx python3 scripts/patch-intl-articles.py           # dry run
  SANITY_TOKEN=xxx python3 scripts/patch-intl-articles.py --apply   # apply
"""
import json, urllib.request, urllib.parse, os, sys, re, time

TOKEN   = os.environ.get("SANITY_TOKEN","").replace("ST=","")
PROJECT = "vbnsqnkg"
BASE    = f"https://{PROJECT}.api.sanity.io/v2024-01-01/data"
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}
DRY_RUN = "--apply" not in sys.argv

def q(query):
    url = f"{BASE}/query/production?query=" + urllib.parse.quote(query)
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {TOKEN}"})
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.loads(r.read())["result"]

def mutate(mutations):
    url  = f"{BASE}/mutate/production"
    body = json.dumps({"mutations": mutations}).encode()
    req  = urllib.request.Request(url, data=body, headers=HEADERS, method="POST")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())

def fetch_og_image(page_url):
    try:
        req = urllib.request.Request(page_url, headers={
            "User-Agent": "Mozilla/5.0 (compatible; DownRange/1.0)",
            "Accept": "text/html",
        })
        with urllib.request.urlopen(req, timeout=10) as r:
            html = r.read(80000).decode("utf-8", errors="ignore")
        m = re.search(r'<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)["\']', html, re.I)
        if not m:
            m = re.search(r'<meta[^>]+content=["\']([^"\']+)["\'][^>]+property=["\']og:image["\']', html, re.I)
        return m.group(1).strip() if m else None
    except:
        return None

def has_structure(body):
    if not body: return False
    h2s = len(re.findall(r'<h2', body, re.I))
    words = len(re.sub(r'<[^>]+>', ' ', body).split())
    return h2s >= 2 and words >= 300

print(f"{'[DRY RUN]' if DRY_RUN else '[LIVE]'} Scanning Canada + Brazil articles...\n")

# Fix the specific broken article first
target = q('*[_type=="canadaContent" && slug.current=="liberals-extend-gun-confiscation-amnesty-while-continuing-seizures"][0]{_id,title,type,active,body,imageUrl,sourceUrl}')
if target:
    print(f"BROKEN ARTICLE: {target.get('title','')[:60]}")
    print(f"  type={target.get('type')} active={target.get('active')} body_len={len(target.get('body','') or '')}")
    fixes = {}
    if target.get('type') != 'article': fixes['type'] = 'article'
    if not target.get('active'):        fixes['active'] = True
    # Force quality-rewrite to process it by setting qualityReviewed=false
    fixes['qualityReviewed'] = False
    if not DRY_RUN:
        mutate([{"patch": {"id": target["_id"], "set": fixes}}])
        print(f"  ✓ Patched: {list(fixes.keys())}")
    else:
        print(f"  [DRY RUN] Would patch: {list(fixes.keys())}")
else:
    print("Broken article not found (may already be fixed)")

print()

# Find all auto-generated Canada/Brazil articles missing structure or images
ca_docs = q('*[_type=="canadaContent" && autoGenerated==true] | order(publishedAt desc) [0...100] {_id,title,slug,body,imageUrl,sourceUrl,qualityReviewed}')
br_docs = q('*[_type=="brazilContent"  && autoGenerated==true] | order(publishedAt desc) [0...100] {_id,title,slug,body,imageUrl,sourceUrl,qualityReviewed}')

all_docs = [("CA", d) for d in ca_docs] + [("BR", d) for d in br_docs]
needs_fix = [(region, d) for region, d in all_docs if not has_structure(d.get("body",""))]
needs_img  = [(region, d) for region, d in all_docs if not d.get("imageUrl") and d.get("sourceUrl")]

print(f"Auto-generated articles: CA={len(ca_docs)} BR={len(br_docs)}")
print(f"Missing body structure:  {len(needs_fix)}")
print(f"Missing images:          {len(needs_img)}\n")

# Mark unstructured articles for re-rewrite (qualityReviewed=false)
print("── Marking unstructured for quality-rewrite ────────────────────")
fixed = 0
for region, doc in needs_fix:
    title = doc.get("title","")[:60]
    body  = doc.get("body","") or ""
    words = len(re.sub(r'<[^>]+>','',body).split())
    h2s   = len(re.findall(r'<h2',body,re.I))
    print(f"  [{region}] {title}")
    print(f"       words={words} h2={h2s}")
    if not DRY_RUN and not doc.get("qualityReviewed") == False:
        try:
            mutate([{"patch": {"id": doc["_id"], "set": {"qualityReviewed": False}}}])
            fixed += 1
        except Exception as e:
            print(f"       ✗ {e}")
    else:
        fixed += 1
    time.sleep(0.2)

print()
print("── Fetching missing images ─────────────────────────────────────")
img_fixed = 0
for region, doc in needs_img[:20]:  # cap at 20 to avoid timeout
    title = doc.get("title","")[:60]
    src   = doc.get("sourceUrl","")
    print(f"  [{region}] {title}")
    og = fetch_og_image(src)
    if og:
        print(f"       OG: {og[:70]}")
        if not DRY_RUN:
            mutate([{"patch": {"id": doc["_id"], "set": {"imageUrl": og}}}])
            img_fixed += 1
    else:
        print(f"       No OG image found")
    time.sleep(0.8)

print()
print("─" * 60)
print(f"Unstructured articles found: {len(needs_fix)}")
print(f"Marked for rewrite:          {fixed}")
print(f"Images fixed:                {img_fixed}")
print(f"Mode: {'DRY RUN' if DRY_RUN else 'LIVE'}")
print("─" * 60)
