export default {
  name: 'newsArticle',
  title: 'News Article',
  type: 'document',
  fields: [
    { name: 'title',      title: 'Title',      type: 'string', validation: R => R.required() },
    { name: 'slug',       title: 'Slug',       type: 'slug', options: { source: 'title' }, validation: R => R.required() },
    { name: 'excerpt',    title: 'Excerpt',    type: 'text', rows: 3 },
    { name: 'summary',    title: 'Summary',    type: 'text', rows: 3 },
    { name: 'body',       title: 'Body',       type: 'array', of: [{ type: 'block' }] },
    // Uploaded Sanity image (for manually authored articles)
    { name: 'heroImage',  title: 'Hero Image (uploaded)', type: 'image', options: { hotspot: true },
      fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }] },
    // External image URL (for AI-aggregated articles from feeds)
    { name: 'imageUrl',   title: 'Image URL (external)', type: 'url',
      description: 'Used for AI-aggregated articles. Sourced from NewsAPI/GNews/RSS.' },
    { name: 'imageAlt',   title: 'Image Alt Text', type: 'string' },
    { name: 'category',   title: 'Category', type: 'string',
      options: { list: ['breaking','news','law','industry','opinion','training','review'] } },
    { name: 'urgencyScore', title: 'Urgency Score (1-10)', type: 'number' },
    { name: 'author',     title: 'Author', type: 'reference', to: [{ type: 'author' }] },
    { name: 'source',     title: 'Source Name', type: 'string' },
    { name: 'externalUrl',title: 'External URL', type: 'url' },
    { name: 'publishedAt',title: 'Published At', type: 'datetime' },
    { name: 'autoGenerated', title: 'AI Generated', type: 'boolean', initialValue: false },
    { name: 'approved',   title: 'Approved for Publish', type: 'boolean', initialValue: true },
    { name: 'tags',       title: 'Tags', type: 'array', of: [{ type: 'string' }] },
    { name: 'relatedStates', title: 'Related States', type: 'array', of: [{ type: 'string' }] },
    { name: 'dedupHash',  title: 'Dedup Hash (internal)', type: 'string' },
  ],
  orderings: [
    { title: 'Published Date, New', name: 'publishedAtDesc', by: [{ field: 'publishedAt', direction: 'desc' }] },
    { title: 'Urgency Score, High', name: 'urgencyDesc',     by: [{ field: 'urgencyScore', direction: 'desc' }] },
  ],
  preview: {
    select: { title: 'title', subtitle: 'category', media: 'heroImage', imgUrl: 'imageUrl' },
    prepare({ title, subtitle, media, imgUrl }) {
      return { title, subtitle: subtitle?.toUpperCase(), media }
    }
  }
}
