import { defineType, defineField } from 'sanity'

export const socialPost = defineType({
  name: 'socialPost',
  title: 'Social Post',
  type: 'document',
  fields: [
    defineField({ name: 'platform',    type: 'string', title: 'Platform',
      options: { list: ['twitter','facebook','instagram','linkedin','threads','bluesky'], layout: 'radio' } }),
    defineField({ name: 'status',      type: 'string', title: 'Status',
      options: { list: ['scheduled','posted','failed','draft','skipped'], layout: 'dropdown' }, initialValue: 'draft' }),
    defineField({ name: 'content',     type: 'text',   title: 'Post Content' }),
    defineField({ name: 'mediaUrl',    type: 'url',    title: 'Media URL (image/video)' }),
    defineField({ name: 'articleSlug', type: 'string', title: 'Source Article Slug' }),
    defineField({ name: 'articleTitle',type: 'string', title: 'Source Article Title' }),
    defineField({ name: 'postUrl',     type: 'url',    title: 'Live Post URL (after posting)' }),
    defineField({ name: 'postId',      type: 'string', title: 'Platform Post ID' }),
    defineField({ name: 'scheduledAt', type: 'datetime', title: 'Scheduled Time' }),
    defineField({ name: 'postedAt',    type: 'datetime', title: 'Posted At' }),
    defineField({ name: 'error',       type: 'string', title: 'Error (if failed)' }),
    defineField({ name: 'metrics',     type: 'object', title: 'Engagement Metrics',
      fields: [
        { name: 'likes',    type: 'number', title: 'Likes' },
        { name: 'reposts',  type: 'number', title: 'Reposts/Shares' },
        { name: 'replies',  type: 'number', title: 'Replies/Comments' },
        { name: 'impressions', type: 'number', title: 'Impressions' },
      ]
    }),
    defineField({ name: 'autoGenerated', type: 'boolean', title: 'Auto-Generated by AI', initialValue: true }),
    defineField({ name: 'urgencyScore',  type: 'number',  title: 'Article Urgency Score' }),
    defineField({ name: 'category',      type: 'string',  title: 'Article Category' }),
  ],
  orderings: [{ title: 'Scheduled (newest)', name: 'scheduledDesc', by: [{ field: 'scheduledAt', direction: 'desc' }] }],
  preview: {
    select: { title: 'content', subtitle: 'platform', media: 'status' },
    prepare({ title, subtitle }) {
      const icons = { twitter:'𝕏', facebook:'f', instagram:'📸', linkedin:'in', threads:'@', bluesky:'🦋' }
      return { title: title?.slice(0,60) + '...', subtitle: `${icons[subtitle] || '?'} ${subtitle?.toUpperCase()} — ${subtitle}` }
    }
  }
})

export const socialConfig = defineType({
  name: 'socialConfig',
  title: 'Social Media Config',
  type: 'document',
  __experimental_actions: ['update', 'publish'],
  fields: [
    defineField({ name: 'enabled',          type: 'boolean', title: 'Social Posting Enabled', initialValue: false }),
    defineField({ name: 'postsPerDay',       type: 'number',  title: 'Posts Per Day (per platform)', initialValue: 3 }),
    defineField({ name: 'postTimes',         type: 'array',   title: 'Post Times (UTC hours)',
      of: [{ type: 'number' }], initialValue: [13, 18, 23] }),
    defineField({ name: 'platforms',         type: 'array',   title: 'Active Platforms',
      of: [{ type: 'string' }] }),
    defineField({ name: 'minUrgencyScore',   type: 'number',  title: 'Min Urgency Score to Post', initialValue: 6 }),
    defineField({ name: 'hashtagSets',       type: 'object',  title: 'Hashtag Sets by Category',
      fields: [
        { name: 'law',     type: 'string', title: 'Law hashtags' },
        { name: 'news',    type: 'string', title: 'News hashtags' },
        { name: 'review',  type: 'string', title: 'Review hashtags' },
        { name: 'default', type: 'string', title: 'Default hashtags' },
      ]
    }),
    defineField({ name: 'twitterHandle',     type: 'string', title: 'Twitter/X Handle' }),
    defineField({ name: 'facebookPageId',    type: 'string', title: 'Facebook Page ID' }),
    defineField({ name: 'instagramHandle',   type: 'string', title: 'Instagram Handle' }),
    defineField({ name: 'threadsHandle',     type: 'string', title: 'Threads Handle' }),
    defineField({ name: 'blueskyHandle',     type: 'string', title: 'Bluesky Handle' }),
    // Per-platform schedule config — stored as JSON string to avoid schema churn
    defineField({ name: 'platforms_config_json', type: 'text', title: 'Per-Platform Schedule Config (JSON)' }),
    // Social profile URLs — shown in header/footer
    defineField({ name: 'socialLinks', type: 'object', title: 'Social Media Profile Links (shown in header/footer)',
      fields: [
        { name: 'bluesky',  type: 'url', title: '🦋 Bluesky URL',          description: 'e.g. https://bsky.app/profile/downrangeco.bsky.social' },
        { name: 'twitter',  type: 'url', title: '𝕏 X/Twitter URL',         description: 'e.g. https://x.com/DownRangeCo' },
        { name: 'facebook', type: 'url', title: 'f Facebook Page URL',      description: 'e.g. https://www.facebook.com/downrangeco' },
        { name: 'instagram', type: 'url', title: '📷 Instagram Profile URL', description: 'e.g. https://www.instagram.com/downrangeconews' },
        { name: 'threads',  type: 'url', title: '@ Threads URL',            description: 'e.g. https://www.threads.net/@downrangeco' },
        { name: 'reddit',   type: 'url', title: '🔴 Reddit Profile/Sub URL', description: 'e.g. https://www.reddit.com/user/DownRangeCo' },
        { name: 'youtube',  type: 'url', title: '▶ YouTube Channel URL',    description: 'e.g. https://www.youtube.com/@DownRangeCo' },
      ]
    }),
  ],
})
